"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

#-----------------------------------
from setuptools import setup, find_packages, Extension

APP = ['mmm/MoneyManager.py']
DATA_FILES = ['resources/myCategDF.csv']
OPTIONS = {'argv_emulation': True,'plist': {'PyRuntimeLocations': ['@executable_path/../Frameworks/libpython3.5m.dylib',
'/Users/wahiba/anaconda/envs/myMoneyManager/lib/libpython3.5m.dylib']},'iconfile':'images/image.icns'}

setup(
    name = 'MyMoneyManager',
    version =          '0.0.1',
    license =          'BSD',
    description =      '',
    author =           "Wahiba Taouali wtaouali@gmail.com",
    app = APP,
    data_files = DATA_FILES,
    options = {'py2app': OPTIONS},
    setup_requires = ['py2app'],
    packages = find_packages(exclude = ("images","resources"))
    )
    #py_modules = ['DataEdition', 'DataImport','DataStats',"func_tools","Params"])
